# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.11.0
#     hooks:
#     -   id: mypy
#         # Mypy가 Django 설정을 읽을 수 있도록 환경 변수를 설정해줍니다.
#         additional_dependencies: ["django-stubs", "types-mysqlclient"]
#         env:
#           DJANGO_SETTINGS_MODULE: config.settings
