# Generated by Django 5.2.5 on 2025-08-16 06:47

from django.db import migrations


def create_initial_seats(apps, schema_editor):
    Seat = apps.get_model("seats", "Seat")
    for i in range(1, 10):
        Seat.objects.create(seat_number=i)


class Migration(migrations.Migration):

    dependencies = [
        ("seats", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_seats),
    ]
